//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string TypeId { get; set; }
    
        public virtual ClothType ClothType { get; set; }
    }
}
